# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\x12\tquadratic\"3\n\x10QuadraticRequest\x12\t\n\x01\x61\x18\x01 \x02(\x01\x12\t\n\x01\x62\x18\x02 \x02(\x01\x12\t\n\x01\x63\x18\x03 \x02(\x01\"\x1c\n\x08Solution\x12\x10\n\x08solution\x18\x01 \x01(\t2\xe9\x01\n\tCalculate\x12?\n\tCalculate\x12\x1b.quadratic.QuadraticRequest\x1a\x13.quadratic.Solution\"\x00\x12L\n\x14\x43\x61lculateStreamReply\x12\x1b.quadratic.QuadraticRequest\x1a\x13.quadratic.Solution\"\x00\x30\x01\x12M\n\x13\x43\x61lculateBidiStream\x12\x1b.quadratic.QuadraticRequest\x1a\x13.quadratic.Solution\"\x00(\x01\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUADRATICREQUEST']._serialized_start=30
  _globals['_QUADRATICREQUEST']._serialized_end=81
  _globals['_SOLUTION']._serialized_start=83
  _globals['_SOLUTION']._serialized_end=111
  _globals['_CALCULATE']._serialized_start=114
  _globals['_CALCULATE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
