# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import quadratic_pb2 as quadratic__pb2


class CalculateStub(object):
    """The QuadraticEquation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/quadratic.Calculate/Calculate',
                request_serializer=quadratic__pb2.QuadraticRequest.SerializeToString,
                response_deserializer=quadratic__pb2.Solution.FromString,
                )
        self.CalculateStreamReply = channel.unary_stream(
                '/quadratic.Calculate/CalculateStreamReply',
                request_serializer=quadratic__pb2.QuadraticRequest.SerializeToString,
                response_deserializer=quadratic__pb2.Solution.FromString,
                )
        self.CalculateBidiStream = channel.stream_stream(
                '/quadratic.Calculate/CalculateBidiStream',
                request_serializer=quadratic__pb2.QuadraticRequest.SerializeToString,
                response_deserializer=quadratic__pb2.Solution.FromString,
                )


class CalculateServicer(object):
    """The QuadraticEquation service definition.
    """

    def Calculate(self, request, context):
        """Sends the coefficients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateStreamReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateBidiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=quadratic__pb2.QuadraticRequest.FromString,
                    response_serializer=quadratic__pb2.Solution.SerializeToString,
            ),
            'CalculateStreamReply': grpc.unary_stream_rpc_method_handler(
                    servicer.CalculateStreamReply,
                    request_deserializer=quadratic__pb2.QuadraticRequest.FromString,
                    response_serializer=quadratic__pb2.Solution.SerializeToString,
            ),
            'CalculateBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.CalculateBidiStream,
                    request_deserializer=quadratic__pb2.QuadraticRequest.FromString,
                    response_serializer=quadratic__pb2.Solution.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quadratic.Calculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculate(object):
    """The QuadraticEquation service definition.
    """

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quadratic.Calculate/Calculate',
            quadratic__pb2.QuadraticRequest.SerializeToString,
            quadratic__pb2.Solution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateStreamReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/quadratic.Calculate/CalculateStreamReply',
            quadratic__pb2.QuadraticRequest.SerializeToString,
            quadratic__pb2.Solution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/quadratic.Calculate/CalculateBidiStream',
            quadratic__pb2.QuadraticRequest.SerializeToString,
            quadratic__pb2.Solution.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
